import React, { Fragment, useState, useContext, useEffect } from 'react';
import Head from 'next/head';
import Header from '@/components/Header.jsx';
import TopCards from '@/components/TopCards.jsx';
import LineChart from '@/components/LineChart.jsx';
import Holdings from '@/components/Holdings.jsx';
import SideBar from '@/components/SideBar';
import { CompoundContext } from '@/contextstore/DataContext';
import Stock from '@/models/stockModel';
import connectDB from '@/components/db';
import { withPageAuthRequired } from '@auth0/nextjs-auth0/client';
import { useUser } from '@auth0/nextjs-auth0/client';
import stockModel from '@/models/stockModel';

const Dashboard = withPageAuthRequired(({ pageProps }) => {
	const [updatedPortfolioData, setUpdatedPortfolioData] = useState();
	const { portfolioData } = pageProps;
	const contextCtx = useContext(CompoundContext);
	const { user } = useUser();

	useEffect(() => {
		const filteredData = portfolioData.filter((stockDoc) => {
			return stockDoc.id === user.sub;
		});
		setUpdatedPortfolioData(filteredData);
	}, [portfolioData, user]);
	console.log(portfolioData);
	console.log(updatedPortfolioData);
	return (
		<Fragment>
			<Head>
				<title>Investor Centre</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<SideBar portfolioData={portfolioData}>
				<Header />
				<div className="px-4 pt-4">
					<h2 className="text-3xl">Performance</h2>
				</div>
				<TopCards portfolioData={updatedPortfolioData} />
				<div className="p-4 grid md:grid-cols-3 grid-cols-1 gap-4">
					<LineChart portfolioData={portfolioData} contextCtx={contextCtx} />
					<Holdings portfolioData={portfolioData} />
				</div>
			</SideBar>
		</Fragment>
	);
});

////////// ENTRY POINT
export const getStaticProps = async () => {
	connectDB();
	const portfolioData = await Stock.find().lean();
	//console.log(portfolioData);

	return {
		props: {
			portfolioData: portfolioData.map((stock) => ({
				name: stock.name,
				email: stock.email,
				id: stock.id,
				ticker: stock.summary.ticker,
				// id: stock._id.toString(),
				positionSize: stock.positionSize,
				avgPurchasePrice: stock.avgPurchasePrice,
				valueAtPurchase: stock.valueAtPurchase,
				lastPrice: stock.lastPrice,
				marketValue: stock.marketValue,
				performance: stock.performance,
				dateOfPurchase: stock.purchaseDate,
			})),
		},
		revalidate: 60,
	};
};

export default Dashboard;
